version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    container_name: keycloak
    environment:
        - KEYCLOAK_ADMIN=root
        - KEYCLOAK_ADMIN_PASSWORD=root
    command: start-dev
    ports:
      - "8080:8080"
    depends_on:
      keycloak-db:
        condition: service_healthy
    networks:
      - network
    healthcheck:
      test: "curl -f http://localhost:8080/admin || exit 1"
      retries: 2
      timeout: 3s

  keycloak-initializer:
    container_name: keycloak-initializer
    build:
      context: keycloak-initializer
      dockerfile: Dockerfile
    image: keycloak-initializer:latest
    networks:
      - network
    ports:
      - "8082:8082"
    depends_on:
      keycloak:
        condition: service_healthy

  keycloak-db:
    image: postgres:latest
    container_name: keycloak-db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=keycloak
    ports:
      - "5432:5432"
    networks:
      - network
    volumes:
      - keycloak_db:/var/lib/data
    healthcheck:
      test: "pg_isready -U root"
      retries: 2
      interval: 3s


networks:
  network:
    driver: bridge

volumes:
  keycloak_db:
    driver: local