version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - "8080:8080"
    networks:
      - network

  keycloak-initializer:
    container_name: keycloak-initializer
    build:
      context: keycloak-initializer
      dockerfile: Dockerfile
    image: keycloak-initializer:latest
    networks:
      - network
    ports:
      - "8083:8083"
    depends_on:
      - keycloak

  backend-client:
    container_name: backend-client
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - ISSUER_URI=http://keycloak:8080/realms/app
      - JWK_SET_URI=http://keycloak:8080/realms/app/protocol/openid-connect/certs
      - AUTH_SERVER_URL=http://keycloak:8080
    networks:
      - network
    ports:
      - "8082:8082"
    depends_on:
      - keycloak
      - database

  database:
    container_name: database
    networks:
      - network
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  frontend-client:
    container_name: frontend-client
    build:
      context: angular-client
      dockerfile: Dockerfile
    networks:
      - network
    ports:
      - "4200:80"
    depends_on:
      - backend-client

  nginx:
    container_name: note-hub-nginx
    networks:
      - network
    build:
      context: nginx
      dockerfile: Dockerfile
    depends_on:
      backend-client:
        condition: service_started
      frontend-client:
        condition: service_started
    ports:
      - "80:80"

networks:
  network:
    driver: bridge

volumes:
  keycloak_db:
    driver: local
