version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=root
      - KEYCLOAK_ADMIN_PASSWORD=root
    command: start-dev
    ports:
      - "8080:8080"
    networks:
      - network
    healthcheck:
      test: "curl -f http://localhost:8080/admin || exit 1"
      retries: 2
      timeout: 3s

  keycloak-initializer:
    container_name: keycloak-initializer
    build:
      context: keycloak-initializer
      dockerfile: Dockerfile
    image: keycloak-initializer:latest
    networks:
      - network
    ports:
      - "8083:8083"
    depends_on:
      keycloak:
        condition: service_healthy

  backend-client:
    container_name: note-hub-backend
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - network
    ports:
      - "8082:8082"
    depends_on:
      - keycloak

  frontend-client:
    container_name: frontend-client
    build:
      context: angular-client
      dockerfile: Dockerfile
    networks:
      - network
    ports:
      - "4200:4200"
    depends_on:
      - backend-client

networks:
  network:
    driver: bridge

volumes:
  keycloak_db:
    driver: local
