spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${OAUTH_RESOURCE_SERVER_JWT_ISSUER_URI}"
          jwk-set-uri: "${OAUTH_RESOURCE_SERVER_JWT_SET_URI}"
  datasource:
    username: "${DATASOURCE_USERNAME}"
    password: "${DATASOURCE_PASSWORD}"
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: update